server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#spring.jpa.pro:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate.hbm2ddl.auto: update
#    showSql: true